routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", "HomeController@index");
Route::post("send-message", "Admin\MessageController@send");

Route::get("/file/{file}", "FileController@show")->where("file", "(.+)");
Route::get("/download/{file}", "FileController@download")->where("file", "(.+)");

Route::resource("news", "NewsController", ["only" => ["index", "show"]]);
Route::resource("gallery", "GalleryController", ["only" => ["index", "show"]]);
// Route::get("message-mailtest/{id}", "Admin\MessageController@testMail");

Route::prefix("admin")->group(function() {
    Auth::routes();

    Route::namespace("Admin")->middleware("auth")->group(function() {
        // Route::get("/", "HomeController@index");
        // Route::get("home", "HomeController@index");
        Route::get("/", "MessageController@inbox");
        Route::get("message", "MessageController@inbox");
        Route::get("message/read-all", "MessageController@readAll");
        Route::get("message/{id}", "MessageController@show");
        Route::post("message/{id}/reply", "MessageController@reply");

        Route::get("setting", "SettingController@index");
        Route::post("account", "SettingController@account");
        Route::post("change-password", "SettingController@changePassword");

        Route::resource("news", "NewsController");
        Route::resource("gallery", "GalleryController");
    });
});

app/Models/Gallery.php
<?php

namespace App\Models;

use App\Models\ModelTraits;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use Ramsey\Uuid\Uuid;

class Gallery extends Model {

    use ModelTraits;

    const IMAGE_DIR = "public/gallery";

    protected $table = 'gallery';

    protected $fillable = ['image', 'description', 'user_id'];

    public static function rules() {
        return [
            'image' => 'required|image',
            'description' => 'required|string',
            'user_id' => 'required|integer',
        ];
    }

    public static function defaultLabel() {
        return [
            'id' => 'ID',
            'image' => 'Gambar',
            'description' => 'Deskripsi',
            'user_id' => 'User',
            'created_at' => 'Dibuat',
            'updated_at' => 'Dirubah',
        ];
    }

    public function beforeSave() {
        // upload images if exists
        if ($this->attributes["image"] instanceof UploadedFile) {
            $path = storage_path("app/".self::IMAGE_DIR);
            $filename = Uuid::uuid1().".".$this->attributes["image"]->extension();
            $img = Image::make($this->attributes["image"]);

            // large image
            $img->resize(800, 800, function ($constraint) {
                $constraint->aspectRatio();
            });
            $img->save("$path/$filename");

            // small image
            $img->resize(400, 400, function ($constraint) {
                $constraint->aspectRatio();
            });
            $img->save("$path/sm-$filename");

            // save filename into database
            $this->image = $filename;
        }
    }

    public function beforeDelete() {
        Storage::delete(self::IMAGE_DIR."/$this->image");
    }

    public function getImageUrlAttribute($size = null) {
        $file = self::IMAGE_DIR."/".($size === null ? "" : "$size-").$this->attributes["image"];

        return asset_file(Storage::exists($file) ? preg_replace("/^public\//", "", $file) : "gallery/default.png");
    }

    public function scopeAuth($query, $user_id = null) {
        if ($user_id === null) {
            $user_id = Auth::user()->id;
        }

        return $query->where("user_id", $user_id);
    }

    public function user() {
        return $this->hasOne(User::class, 'id', 'user_id');
    }
}

app/Http/Controllers/Admin/GalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Gallery;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class GalleryController extends Controller {

    public function index() {
        $data = Gallery::auth(Auth::user()->id)->orderBy("created_at", "desc")->paginate();

        return view("admin.gallery.list", compact("data"));
    }

    public function create() {
        $model = [];

        return view("admin.gallery.add", compact("model"));
    }

    public function store(Request $request) {
        Gallery::createOrFail(array_merge($request->all(), [
            "user_id" => Auth::user()->id,
        ]));

        return redirect("admin/gallery");
    }

    public function edit($id) {
        $model = Gallery::findOrFail($id);

        return view("admin.gallery.edit", compact("model"));
    }

    public function update(Request $request, $id) {
        Gallery::findOrFail($id)->updateOrFail($request->all());

        return redirect("admin/gallery");
    }

    public function destroy($id) {
        Gallery::findOrFail($id)->delete($id);

        return redirect("admin/gallery");
    }
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Gallery;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class GalleryController extends Controller {

    public function index() {
        $data = Gallery::orderBy("created_at", "desc")->paginate(12);

        return view("gallery.list", compact("data"));
    }

    public function show($id) {
        $model = Gallery::findOrFail($id);

        return view("gallery.show", compact("model"));
    }
}

resources/views/admin/gallery/add.blade.php
@extends("admin.app")

@section("page-title", "Tambah Galeri")

@section("content")
  <div class="mb4 tr" style="margin-top: -62px">
    <a href="{{ url("admin/gallery") }}" class="btn btn-default">
      <i class="glyphicon glyphicon-share-alt"></i> Kembali
    </a>
  </div>

  {!! Form::model([], ["url" => url("admin/gallery"), 'files' => true]) !!}
    @include("admin.gallery.form", get_defined_vars())
  {!! Form::close() !!}
@endsection

resources/views/admin/gallery/edit.blade.php
@extends("admin.app")

@section("page-title")
  Galeri
@endsection

@section("content")
  <div class="mb4 tr" style="margin-top: -62px">
    <a href="{{ url("admin/gallery") }}" class="btn btn-default">
      <i class="glyphicon glyphicon-share-alt"></i> Kembali
    </a>
  </div>

  {!! Form::model($model, ["url" => url("admin/gallery/$model->id"), "method" => "PUT", 'files' => true]) !!}
    @include("admin.gallery.form", get_defined_vars())
  {!! Form::close() !!}
@endsection

resources/views/admin/gallery/form.blade.php
<?php

use App\Models\Gallery;

?>

<div class="form-group row">
  {!! Form::label("image", Gallery::label("image"), [
    "class" => "col-form-label col-sm-2 tr",
  ]) !!}

  <div class="col-sm-6">
    {!! Form::file("image", null, ["class" => "form-control"]) !!}

    @if ($model instanceof Gallery && $model->image !== null)
      <div class="dt mt2">
        <div class="thumbnail fixed-thumbnail-md">
          <img src="{{ $model->image_url }}" style="max-height: 100%; max-width: 100%" />
        </div>
      </div>
    @endif
  </div>
</div>

<div class="form-group row">
  {!! Form::label("description", Gallery::label("description"), [
    "class" => "col-form-label col-sm-2 tr",
  ]) !!}

  <div class="col-sm-6">
    {!! Form::textarea("description", null, ["class" => "form-control"]) !!}
  </div>
</div>

<div class="form-group row">
  <div class="col-sm-offset-2 col-sm-10">
    <button type="submit" class="btn btn-secondary">Simpan</button>
  </div>
</div>

resources/views/admin/gallery/list.blade.php
@extends("admin.app")

<?php

use App\Models\Gallery;

?>

@section("page-title", "Galeri")

@section("content")
  <div class="mb4 tr" style="margin-top: -62px">
    <a href="{{ url("admin/gallery/create") }}" class="btn btn-success">
      <i class="glyphicon glyphicon-plus"></i> Tambah
    </a>
  </div>

  @if(count($data) > 0)
    @foreach($data as $item)
      <div class="br2 ba b--moon-gray pa3 bg-white shadow-hover mb3">
        <div class="row">
          <div class="col-sm-10">
            <div class="cf">
              <div class="fl">
                <div class="thumbnail ma0">
                  <div class="img-thumb bg-white shadow-hover" style="height: 100px; width: 100px">
                    <img src="{{ $item->getImageUrlAttribute("sm") }}" />
                  </div>
                </div>
              </div>
              <div class="fl w-80 pl3">
                <div class="word-wrap">{{ substr(strip_tags($item->description), 0, 200) }}</div>
              </div>
            </div>
          </div>
          <div class="col-sm-2">
            <action href="{{ url("admin/gallery/$item->id/edit") }}" cls="btn btn-sm btn-info mh1">
              <i class="glyphicon glyphicon-edit white"></i> Edit
            </action>
            <action href="{{ url("admin/gallery/$item->id") }}"
              cls="btn btn-sm btn-danger mh1"
              method="DELETE"
              onClick="return confirm('Anda yakin ?')"
            >
              <i class="glyphicon glyphicon-remove white"></i> Delete
            </action>
          </div>
        </div>
      </div>
    @endforeach

    {{ $data->links() }}
  @else
    @include("utils.empty")
  @endif
@endsection