routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", "HomeController@index");
Route::post("send-message", "Admin\MessageController@send");

Route::get("/file/{file}", "FileController@show")->where("file", "(.+)");
Route::get("/download/{file}", "FileController@download")->where("file", "(.+)");

Route::resource("news", "NewsController", ["only" => ["index", "show"]]);
Route::resource("gallery", "GalleryController", ["only" => ["index", "show"]]);
// Route::get("message-mailtest/{id}", "Admin\MessageController@testMail");

Route::prefix("admin")->group(function() {
    Auth::routes();

    Route::namespace("Admin")->middleware("auth")->group(function() {
        // Route::get("/", "HomeController@index");
        // Route::get("home", "HomeController@index");
        Route::get("/", "MessageController@inbox");
        Route::get("message", "MessageController@inbox");
        Route::get("message/read-all", "MessageController@readAll");
        Route::get("message/{id}", "MessageController@show");
        Route::post("message/{id}/reply", "MessageController@reply");

        Route::get("setting", "SettingController@index");
        Route::post("account", "SettingController@account");
        Route::post("change-password", "SettingController@changePassword");

        Route::resource("news", "NewsController");
        Route::resource("gallery", "GalleryController");
    });
});

app/Models/News.php
<?php

namespace App\Models;

use App\Models\ModelTraits;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use Ramsey\Uuid\Uuid;

class News extends Model {

    use ModelTraits;

    const IMAGE_DIR = "public/news";

    protected $table = 'news';

    protected $fillable = ['title', 'content', 'cover', 'user_id'];

    public static function rules() {
        return [
            'title' => 'required|string|max:255',
            'content' => 'required|string',
            'cover' => 'required|image',
            'user_id' => 'required|integer',
        ];
    }

    public static function defaultLabel() {
        return [
            'id' => 'ID Berita',
            'title' => 'Judul',
            'content' => 'Konten',
            'cover' => 'Sampul',
            'user_id' => 'User',
            'created_at' => 'Dibuat',
            'updated_at' => 'Dirubah',
        ];
    }

    public function beforeSave() {
        // upload images if exists
        if ($this->attributes["cover"] instanceof UploadedFile) {
            $path = storage_path("app/".self::IMAGE_DIR);
            $filename = Uuid::uuid1().".".$this->attributes["cover"]->extension();
            $img = Image::make($this->attributes["cover"]);

            // large image
            $img->resize(600, 600, function ($constraint) {
                $constraint->aspectRatio();
            });
            $img->save("$path/$filename");

            // small image
            $img->resize(200, 200, function ($constraint) {
                $constraint->aspectRatio();
            });
            $img->save("$path/sm-$filename");

            // save filename into database
            $this->cover = $filename;
        }
    }

    public function beforeDelete() {
        Storage::delete(self::IMAGE_DIR."/$this->cover");
    }

    public function getCoverUrlAttribute($size = null) {
        $file = self::IMAGE_DIR."/".($size === null ? "" : "$size-").$this->attributes["cover"];

        return asset_file(Storage::exists($file) ? preg_replace("/^public\//", "", $file) : "news/default.png");
    }

    public function getSeoIdAttribute() {
        return "$this->id-".str_replace("_", "-", snake_case($this->title));
    }

    public function getShortContentAttribute($length = null) {
        $content = strip_tags($this->content);
        $length = $length === null ? 200 : $length;

        return strlen($content) > $length ? substr($content, 0, $length)."..." : $content;
    }

    public function scopeSearch($query, $search = "") {
        if (strlen($search) > 0) {
            $query->where(DB::raw("lower(title)"), "like", "%".strtolower($search)."%");
        }

        return $query;
    }

    public function scopeAuth($query, $user_id = null) {
        if ($user_id === null) {
            $user_id = Auth::user()->id;
        }

        return $query->where("user_id", $user_id);
    }

    public function user() {
        return $this->hasOne(User::class, 'id', 'user_id');
    }
}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\News;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NewsController extends Controller {

    public function index() {
        $data = News::auth(Auth::user()->id)->orderBy("created_at", "desc")->paginate();

        return view("admin.news.list", compact("data"));
    }

    public function create() {
        $model = [];

        return view("admin.news.add", compact("model"));
    }

    public function store(Request $request) {
        News::createOrFail(array_merge($request->all(), [
            "user_id" => Auth::user()->id,
        ]));

        return redirect("admin/news");
    }

    public function edit($id) {
        $model = News::findOrFail($id);

        return view("admin.news.edit", compact("model"));
    }

    public function update(Request $request, $id) {
        News::findOrFail($id)->updateOrFail($request->all());

        return redirect("admin/news");
    }

    public function destroy($id) {
        News::findOrFail($id)->delete($id);

        return redirect("admin/news");
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\News;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NewsController extends Controller {

    public function index(Request $req) {
        $data = News::search($req->search)->orderBy("created_at", "desc")->paginate(5);
        $newest = News::orderBy("created_at", "desc")->take(5)->get();

        return view("news.list", compact("data", "newest"));
    }

    public function show($seo_id) {
        preg_match_all("/(\d+)\-.+/", $seo_id, $match);
        $model = News::findOrFail($match[1][0]);

        if ($model->seo_id !== $seo_id) {
            return abort(404);
        }

        return view("news.show", compact("model"));
    }
}

resources/views/news/item.blade.php
<div class="br2 ba b--moon-gray pa3 bg-white shadow-hover">
  <div class="row">
    <div class="col-sm-3">
      <div class="img-thumb img-thumb-sm">
        <img src="{{ $news->getCoverUrlAttribute("sm") }}" />
      </div>
    </div>
    <div class="col-sm-6">
      <p class="b f3">{{ $news->title }}</p>
      <div>{{ substr(strip_tags($news->content), 0, 100) }}</div>
    </div>
    <div class="col-sm-3">
      <action href="{{ url("admin/news/$news->id/edit") }}" cls="btn btn-sm btn-info mh1">
        <i class="glyphicon glyphicon-edit white"></i> Edit
      </action>
      <action href="{{ url("admin/news/$news->id") }}"
        cls="btn btn-sm btn-danger mh1"
        method="DELETE"
        onClick="return confirm('Anda yakin ?')"
      >
        <i class="glyphicon glyphicon-remove white"></i> Delete
      </action>
    </div>
  </div>
</div>

resources/views/news/list.blade.php
@extends("app")

<?php

use App\Models\News;

$searchQuery = Request::input("search");

?>

@section("page-title")
  <i class="glyphicon glyphicon-list-alt"></i> News
@endsection

@section("content")
  @if (count($newest) > 0)
    <div class="row">
      <div class="col-md-6 ph5 br b--moon-gray">
        <div class="news-slider">
          @foreach($newest as $item)
            <div class="relative img-thumb pa0" style="width: 100%; height: 400px; padding: 0">
              <a href="{{ url("news/$item->seoId") }}">
                <img data-lazy="{{ $item->cover_url }}" />
                <div class="absolute z-max bg-black-80 ph4 pt3 pb4 w-100 left-0 shadow-1 bottom-0">
                  <div class="white b f3">{{ $item->title }}</div>
                  <div class="light-gray f4 lh-title">{{ $item->short_content }}</div>
                </div>
              </a>
            </div>
          @endforeach
        </div>
      </div>
      <div class="col-md-6">
        <div class="pb3 bb b--moon-gray mt2">
          {{ Form::open(["method" => "GET"]) }}
            <div class="input-group">
              <input
                type="text"
                name="search"
                class="form-control"
                placeholder="Pencarian"
                value="{{ $searchQuery }}"
              />
              <span class="input-group-btn">
                @if (strlen($searchQuery) > 0)
                  <a href="{{ url("news") }}" class="btn btn-default">
                    <i class="glyphicon glyphicon-remove"></i>
                  </a>
                @endif
                <button class="btn btn-default" type="submit">
                  <i class="glyphicon glyphicon-search"></i>
                </button>
              </span>
            </div>
          {{ Form::close() }}
        </div>

        @foreach($data as $item)
          <a href="{{ url("news/$item->seoId") }}" class="bb b--moon-gray db pa3">
            <div class="b f3">{{ $item->title }}</div>
            <div class="word-wrap gray f4">
              {{ $item->getShortContentAttribute(80) }}
            </div>
          </a>
        @endforeach

        <div class="tc">
          {{ $data->links() }}
        </div>
      </div>
    </div>
  @else
    @include("utils.empty")
  @endif
@endsection

@push("css")
  <link rel="stylesheet" href="{{ asset("js/slick/slick.css") }}">
  <link rel="stylesheet" href="{{ asset("js/slick/slick-theme.css") }}">
@endpush

@push("js")
  <script src="{{ asset("js/slick/slick.min.js") }}"></script>
  <script type="text/javascript">
    $('.news-slider').slick({
      lazyLoad: 'ondemand',
      dots: true,
      autoplay: true,
    });
  </script>
@endpush

resources/views/news/show.blade.php
@extends("app")

<?php

use App\Models\News;

?>

@section("content")
  <div class="row bb b--moon-gray mv3 mh0 pb3">
    <div class="col-xs-8 col-md-10">
      <h3 class="ma0">{{ $model->title }}</h3>
    </div>
    <div class="col-xs-4 col-md-2 dtc v-btm">
      <div class="tr">
        <div class="gray">
          {{ $model->user->name }}
        </div>
        <div class="gray i f4">
          {{ date("H:i - d M Y", strtotime($model->created_at)) }}
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4 fr-m fr-l">
      <div class="thumbnail bg-white">
        <img src="{{ $model->coverUrl }}" />
      </div>
    </div>
    <div class="col-sm-8 br b--moon-gray" style="min-height: 400px">
      <div class="table-responsive">
        {!! $model->content !!}
      </div>
    </div>
  </div>
@endsection